### PR TITLE
added more colors

### PR DESCRIPTION
**Pull request by AkhileshJyotishi**
1. added more colors to the script file in color.sh
2. added a file named username.sh to find the username of the wifi we are using currently
3. wrote  a script delete_binary.sh and added it ,it will delete all binary files in present working directory
4. wrote a weather.sh script which tells weather of current location 
fixes:
 #1 
 #9
  #6
  #8

### CODE REVIEW

**Comment by Animeshz** [comment]
I believe there are more colors to add, can you recheck please?

**Comment by AkhileshJyotishi** [comment]
sir reupdated the file.

**Comment by Animeshz** [comment]
wifi-ssid script doesn't work, variable assignment can't contain spaces in bash.

**Comment by Animeshz** [comment]
Don't you test the script before committing? Assigned 3+3, update the wifi-ssid script to evaluate that one as well.

**Comment by AkhileshJyotishi** [comment]
sorry  for inconvinience,just changed it in last moment

**Comment by AkhileshJyotishi** [comment]
sir updated the wifi-ssid(#9 ) and created a weather.sh file to fix #8

**Comment by Animeshz** [comment]
Read #8 again, there's more thing to do, and make a separate PR for that. You should never add multiple issue fixes in a single PR in public.

**Pull request closed without merging**
